### ISSUE TITLE
Wrong UI ?

### ISSUE THREAD

**Issue by yongkangchen** [pitaj/wengit#2]
Is there any screenshots about `wengit`?
I install and running, is shows:
<img width="775" alt="94450710-366c-439a-bef9-a521448a02ea" src="https://cloud.githubusercontent.com/assets/704762/9348993/bb7f06c0-4671-11e5-81d4-a30555ca930b.png">

Am I missing something? BTW, I'm using mac os x 10.10.5.

**Comment by pitaj** [comment]
Are there any errors in the console? Right click to open dev tools.

**Comment by yongkangchen** [comment]
No errors in console and `dev tools console`.

2015-08-19 13:00 GMT+08:00 Peter Jaszkowiak <notifications@github.com>:

**Comment by pitaj** [comment]
Try `npm update` in the `wengit` directory. I think the problem was an issue with the Riot library, not with my code.
